### ISSUE TITLE
Content Change To Application [ NAME ] needed.

### ISSUE THREAD

**Issue by sprsr** [AwaitQuality/windowsonarm#10]
### Application Name

Vivado

### Category Name

development

### Company

Xillinx 

### App URL

https://www.xilinx.com/support/download.html

### Tags

EDA

### Description

Vivado Design Suite is a software suite for synthesis and analysis of hardware description language designs, superseding Xilinx ISE with additional features for system on a chip development and high-level synthesis. Vivado represents a ground-up rewrite and re-thinking of the entire design flow. Like the later versions of ISE, Vivado includes the in-built logic simulator. 

### Tell us more

Have experienced some driver compatibility issues.  I am able to develop and run synthesis.

**Comment by OpenSource03** [comment]
Hello. Please note that this is not the place to contribute by posting new apps. You can do so by clicking the Post application button on the website :)

**Comment by sprsr** [comment]
Apologies :)
