### ISSUE TITLE
Content Change To Application Google Drive for Desktop needed. 

### ISSUE THREAD

**Issue by andyanderson** [AwaitQuality/windowsonarm#11]
### Application Name

Google Drive for Desktop 

### Category Name

Release

### Company

Google

### App URL

https://www.google.com/drive/

### Community URL

https://www.googlecloudcommunity.com/gc/Workspace-Q-A/Google-Desktop-on-Windows-ARM/m-p/170725

### Description

Google is not supporting Google Drive for Desktop on ARM architectures “due to low adoption”.

**Comment by andyanderson** [comment]
Latest version just downloaded puts up this message:

<img width="276" alt="image" src="https://github.com/user-attachments/assets/666b5291-d983-4fd2-b6b4-01db0ffbcb45">

**Comment by OpenSource03** [comment]
Thanks! I've updated it :)
