### ISSUE TITLE
Content Change To Application Maple 2024 needed.

### ISSUE THREAD

**Issue by agascoig** [AwaitQuality/windowsonarm#22]
### Application Name

Maple 2024

### Company

Maplesot

### Tell us more

This application works only intermittently in 'Very Strict Multicore' mode.

**Comment by OpenSource03** [comment]
Hi, what is Very Strict Multicore mode?

**Comment by agascoig** [comment]
For maplew.exe:

Click Properties -> Compatibility Tab -> Change Emulation Settings -> Change Emulation Settings -> Used Advanced settings checkbox ->
"Change how the application uses multiple CPU cores" -> "Very strict multi-core operation"

________________________________

**Comment by OpenSource03** [comment]
Thanks. I've updated the description.
