### ISSUE TITLE
Content Change To Application Adobe Premiere Pro needed.

### ISSUE THREAD

**Issue by stbaxter** [AwaitQuality/windowsonarm#24]
### Application Name

 Adobe Premiere Pro

### Company

Adobe

### App URL

https://apps.microsoft.com/detail/xpdlpkwg9sw2wd?ocid=pdpshare&hl=en-gb&gl=AU

### Description

Hi there, just a heads up the Adobe announced an update to Premiere Pro

https://www.windowscentral.com/software-apps/windows-11/windows-11-laptops-with-snapdragon-x-arm-chips-can-now-run-adobe-premiere-pro-under-emulation

**Comment by OpenSource03** [comment]
Thanks, updated
