### ISSUE TITLE
[Bug]: Site is not working

### ISSUE THREAD

**Issue by csc0ttbrown** [AwaitQuality/windowsonarm#27]
### Bug description

The list of apps at [windowsonarm.org](http://windowsonarm.org/) does not work.

### Expected behavior

Site should load dynamic list of apps.

### What browsers are you seeing the problem on?

Chromium based

### Relevant log output

None needed

**Comment by OpenSource03** [comment]
Fixed, we'll be migrating to a new db to avoid this problem in the future.
