### ISSUE TITLE
Content Change To Application PDF X-Change Editor needed.

### ISSUE THREAD

**Issue by Mitia99** [AwaitQuality/windowsonarm#33]
### Application Name

PDF-XChange Editor

### Description

The Application Name is wrong.
It's **PDF-XChange Editor** not **PDF X-Change Editor**. See [their website](https://pdf-xchange.eu/pdf-xchange-editor/).
Users who use search feature may not find the program.

### Tell us more
Typos in description should be fixed as well 

![image](https://github.com/user-attachments/assets/8ae76774-445c-4b9d-aa2a-2eb431e7e07a)

Thank you,

**Comment by OpenSource03** [comment]
Thanks for noticing. It's been updated.

**Comment by Mitia99** [comment]
Thanks for the update.

Here's its icon URL btw

https://images-eds-ssl.xboxlive.com/image?url=4rt9.lXDC4H_93laV1_eHHFT949fUipzkiFOBH3fAiZZUCdYojwUyX2aTonS1aIwMrx6NUIsHfUHSLzjGJFxxuJ37Ra6wwlqXNXon3qke751GRPwHg.e1TAS3VS4EwaJeynX1NV9sejRa90OElPEve_g0M2IkcH4.wk11o.9ENo-&format=source
