### ISSUE TITLE
Content Change To Application Cisco Webex needed.

### ISSUE THREAD

**Issue by timetrvlr** [AwaitQuality/windowsonarm#48]
### Application Name

Webex

### What is the status of the app's arm support

Emulated

### Company

Cisco

### App URL

https://help.webex.com/es-co/article/krgc3ab/Aplicaci%C3%B3n-de-Webex%7C-Descargar-la-aplicaci%C3%B3n-de-escritorio-o-m%C3%B3vil

### Description

Hi!

I think this app was wrongly categorized as Native because I can´t find that version for download in its website. The only windows version I've found was x64.

Don't get me wrong, it works, but I think it's emulated.

### Tell us more

In the task manager it also says x64.

**Comment by OpenSource03** [comment]
Correct. I've updated the status. Thanks.
