### ISSUE TITLE
Content Change To Application AutoCAD needed.

### ISSUE THREAD

**Issue by Mitia99** [AwaitQuality/windowsonarm#50]
### Application Name

AutoCAD

### What is the status of the app's arm support

Emulated

### Company

Autodesk

### Description

[Worksonwoa](https://www.worksonwoa.com/applications/search/?query=Autocad) says that it works

![Screenshot_20241020_082938](https://github.com/user-attachments/assets/1403eebe-1af9-4c5d-80b9-e20d8c072ae4)

**Comment by OpenSource03** [comment]
What does work mean? Is it emulated or natively supported?

**Comment by Mitia99** [comment]
@OpenSource03 I personally don't use AutoCad but I came across the wrong [](https://windowsonarm.org/) information (not supported) through [Reddit](https://www.reddit.com/r/snapdragon/comments/1du2net/does_matlab_solidworks_and_autocad_work_on/). It's probably emulated as there's no AutoCAD ARM version yet

**Comment by OpenSource03** [comment]
Thanks, that's been updated :)
