### ISSUE TITLE
Rstudio version 2024.09.0+375 runs fine on a Lenovo Slim snapdragon system.

### ISSUE THREAD

**Issue by jrthompson54** [AwaitQuality/windowsonarm#51]
### Application Name

RStudio

### What is the status of the app's arm support

None

### Description

Rstudio version 2024.09.0+375 runs fine on a Lenovo Slim snapdragon system.

**Comment by OpenSource03** [comment]
Hi, so is it running under emulation or native?

According to a user comment, it's under emulation. Are you able to verify that?

**Comment by OpenSource03** [comment]
Closed as no further comment was received.
