### ISSUE TITLE
Content Change To Application StarMoney needed.

### ISSUE THREAD

**Issue by SvenPStarFinanz** [AwaitQuality/windowsonarm#53]
### Application Name

StarMoney

### What is the status of the app's arm support

Emulated

### Category Name

German Home Banking Software

### Company

Star Finanz Software-Entwicklung und Vertriebs GmbH

### App URL

https://www.starmoney.de

### Tags

Home Banking HBCI FINTS Money Geld

### Description

StarMoney is a personal finance management software developed by Star Finanz, designed to help users manage their finances, track expenses, and handle online banking transactions. It offers features such as account aggregation, budget planning, financial reporting, and transaction categorization. StarMoney supports multiple bank accounts and financial institutions, allowing users to view and manage all their financial information in one place. The software is known for its user-friendly interface and robust security measures, making it a popular choice for individuals seeking to streamline their financial management and gain better control over their personal finances.

### Tell us more

Whether StarMoney runs on ARM is a matter of driver updates. Since a recent update from Microsoft, StarMoney runs on ARM, although emulated:
https://www.drwindows.de/xf/threads/surface-laptop-7-umfangreiches-firmware-update-f%C3%BCr-das-arm-ger%C3%A4t.189514
https://hilfe.starmoney.de/hc/de/articles/16518623699740-Lauff%C3%A4higkeit-von-StarMoney-auf-PCs-mit-Snapdragon-Prozessor

**Comment by OpenSource03** [comment]
Updated, thanks.
