### ISSUE TITLE
Content Change To Application Telegram needed.

### ISSUE THREAD

**Issue by timetrvlr** [AwaitQuality/windowsonarm#57]
### Application Name

Telegram

### What is the status of the app's arm support

Native

### Category Name

Social

### Company

Telegram

### App URL

https://github.com/telegramdesktop/tdesktop/releases/tag/v5.7.2

### Community URL

https://telegram.org/

### Icon URL

https://logospng.org/download/telegram/logo-telegram-4096.png

### Description

Telegram is a cloud-based instant messaging app known for its emphasis on speed, security, and privacy. It allows users to send text messages, voice messages, multimedia files, and make voice and video calls. Telegram supports the creation of group chats with up to 200,000 members and channels for broadcasting to unlimited audiences. One of its key features is end-to-end encryption for Secret Chats, ensuring that messages can only be read by the intended recipients. Telegram also offers a variety of bots, stickers, and an open API, enabling developers to create custom tools and integrations. It is available on multiple platforms, including Android, iOS, Windows, macOS, and Linux.

### Tell us more

A native ARM version of telegram has been deployed. There is an article from a reputable source: https://www.windowscentral.com/software-apps/telegram-launches-native-windows-on-arm-support

I also have been able to install it successfully!

**Comment by OpenSource03** [comment]
Updated, thanks
