### ISSUE TITLE
Content Change To Application Apple Music needed.

### ISSUE THREAD

**Issue by timetrvlr** [AwaitQuality/windowsonarm#59]
### Application Name

Apple Music

### What is the status of the app's arm support

Emulated

### Category Name

Entertainment

### Company

Apple

### App URL

https://apps.microsoft.com/detail/9pfhdd62mxs1?hl=en-US&gl=US

### Tell us more

Hi! I think the app is working via emulation, not as a native version.

Here’s a screenshot of my test.

![image](https://github.com/user-attachments/assets/5bd86ca0-7539-492b-a294-1e41e4d465e0)

**Comment by OpenSource03** [comment]
Corrected, thanks.
