### ISSUE TITLE
Content Change To Application Quick Share by Google needed.

### ISSUE THREAD

**Issue by GTMoraes** [AwaitQuality/windowsonarm#64]
### Application Name

Quick Share by Google

### What is the status of the app's arm support

Emulated

### Category Name

Productivity

### Company

Google

### App URL

https://www.android.com/better-together/quick-share-app/

### Icon URL

https://cdn.windowsonarm.org/windowsonarm/uploads/user_2oDahEZlRdNvhpveOVbu5vQrHGT/1730890051929-download.png

### Tags

file-synchronization

### Description

Google Quick Share

### Tell us more

The installer fails, but you can install it on a x86 machine, then copy the Quick Share installation folder to the ARM64 Windows, and it'll fully work, just fine.

Quick Share, by itself, is supported through emulation. Only the installer that isn't.

**Comment by CanePlayz** [comment]
It is now actually natively support.

**Comment by OpenSource03** [comment]
Updated, thanks.
