### ISSUE TITLE
Content Change To Application [ Quick Share ] needed.

### ISSUE THREAD

**Issue by ghost** [AwaitQuality/windowsonarm#68]
### Application Name

Quick Share by Google

### What is the status of the app's arm support

Emulated

### Company

Google LLC

### App URL

https://www.android.com/intl/en_ca/better-together/quick-share-app/

### Community URL

https://windowsonarm.org/2bb988a2-0b86-4b82-8968-deefa00eafe4

### Description

Sending files to and from Android devices. 

### Tell us more

I see duplicate Quick Share apps in the list: one that says it's native and the other that says it's not supported. So only one of them should be kept; I think the one called Quick Share by Google by owen_vdl should be kept and the other one removed. Also, its state is emulated at the time of writing.

**Comment by OpenSource03** [comment]
I see. I've removed the one from owen_vdl as it's the most recent one. Status is also updated to emulated as per multiple reports. Thanks.
