### ISSUE TITLE
Content Change To Application Quick Share needed.

### ISSUE THREAD

**Issue by ghost** [AwaitQuality/windowsonarm#71]
### Application Name

Quick Share

### What is the status of the app's arm support

Emulated

### Company

Samsung, Google

### App URL

https://windowsonarm.org/8b50e95e-95f4-4fe8-bb07-237f156721d0

### Community URL

https://windowsonarm.org/8b50e95e-95f4-4fe8-bb07-237f156721d0

### Description

Sharing files between Android and PC

### Tell us more

Please delete the Quick share app by ronak_90873, and change the one by owen_vdl to Emulated. One contributer replied "updated",  but it hasn't been.

**Comment by OpenSource03** [comment]
Already completed as per #68
