### ISSUE TITLE
Content Change To Application Node Version Manager (NVM) needed.

### ISSUE THREAD

**Issue by milkeryildirim** [AwaitQuality/windowsonarm#75]
### Application Name

Node Version Manager (NVM)

### What is the status of the app's arm support

Emulated

### App URL

https://github.com/coreybutler/nvm-windows

### Description

It is not possible to find the Windows ARM64 version of NVM, as reported by Tosha, either on the official website or in any other forks. The report appears to be incorrect. NVM runs only in emulated mode on Windows 11 ARM64.

**Comment by OpenSource03** [comment]
I've been able to verify that. The status has been updated.
