### ISSUE TITLE
Content Change To Application [ Visual Studio 2022] needed.

### ISSUE THREAD

**Issue by MikeFarrington** [AwaitQuality/windowsonarm#84]
### Application Name

Visual Studio 2022

### What is the status of the app's arm support

Native

### Category Name

Development

### Company

Microsoft, Inc.

### App URL

https://visualstudio.microsoft.com/

### Community URL

https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022

### Icon URL

https://upload.wikimedia.org/wikipedia/commons/2/2c/Visual_Studio_Icon_2022.svg

### Description

Since version 17.4 in June of 2024, Visual Studio has had native ARM support.  It is now up to v17.12.  This is a distinct product from Visual Studio Code which is a lightweight code editor.

**Comment by OpenSource03** [comment]
Hi. I don't see this app on the website. Note that issues section is only for reporting issues for existing apps. For non-existing apps, click on request app button on the website 😊
